### ISSUE TITLE
Seminar pages move from main page to archive before time of talk

### ISSUE THREAD

**Issue by jchate6** [LCOGT/main_website#10]
I believe that the seminar pages might be moved into archive at the UT time of the talk rather than the local time of the talk.  This is problematic for people who might be checking to see what today's seminar is about. I'd like talks to not move into the archive until after the day of the talk. (i.e. if the talk is on 01/15 then the talk remains at the top of the list of seminars until 01/16) I would prefer for this to be local time, but even if this were a UT transition it should still be late enough to not be an issue anymore.

**Comment by zemogle** [comment]
Deployed
