### ISSUE TITLE
Updates to dynamical elements on the Science Seminar page

### ISSUE THREAD

**Issue by jchate6** [LCOGT/main_website#4]
- [x]  On the main seminar page, list upcoming seminars next -> last from top to bottom
- [x]  On a speaker page change link text to "Return to Science Seminar page" rather than "Science / Science Seminar"
- [x] Upcoming seminars disappear on the day of the seminar (before their seminar happens). 

I am unclear if seminars disappearing early is because seminar times are often 3:30AM rather than 15:30, or what causes this transition. Either way, having the "current seminar" last until end of day Santa Barbara time would be very convenient. I've set the next one for 15:30 as an experiment. I'll try to notice when it disappears from the site.

**Comment by zemogle** [comment]
When you say "next > last" do you mean "next > future seminars" or "next > past seminars"?

I'll look at the other points now.

**Comment by zemogle** [comment]
I think I've addressed all of these with the commit 35abd159fbf1c2116089ec354dffdaab1bde7597

I'll build and deploy it soon.

**Comment by jchate6** [comment]
I meant something like this:
--upcoming seminar
--one after that
--one after that
...
-- last scheduled seminar (furthest in the future)

Thanks!

**Comment by zemogle** [comment]
I figured that was what you were looking for. I've updated the site now.
